import streamlit as st

st.markdown('## Documentación:')
st.markdown('*Todas las graficas se han codeado conn plotly que permite navegarlas desntro de la pestaña y exportarlas al ordenador.*')
st.markdown('*Los colores de los servicios estan oreviamente establecidos y los comparten todas las graficas.*')
st.markdown('### General:')
st.markdown('* Selector de Outliers para estudios especificos.')
st.markdown('* Vision general de la progresión de ventas de la empresa con opcion de seleccionar el rango de años.')
st.markdown('* El Start hace referencia a año/01/01 y el Stop a año/12/31.')
st.markdown('* El promedio, desviacion standar y mediana se calculan en el rango seleccionado.')
st.markdown('### Clientes:')
st.markdown('* Selector de Outliers para estudios especificos.')
st.markdown('* Clientes permite estudiar a cada cliente de forma individual.')
st.markdown('* El rango de años unicamente afecta a la gráfica de *Importe de Ventas por Cliente*.')
st.markdown('* Esto se debe a que daria error si el id_cliente no existiese en el rango seleccionado.')
st.markdown('* Hay un rango de clientes para la visualización de la primera grafica.')
st.markdown('* La segunda grafica  es un desglose del todos los servicios comprados por el cliente.')
st.markdown('* La tercera grafica es unna linea temporal general.')
st.markdown('* La cuarta grafica permite seleccionar con el multiselect varios servicios a visualizar a la vez.')
st.markdown('')
st.markdown('## Servicios:')
st.markdown('* Selector de Outliers para estudios especificos.')
st.markdown('* Esta pestaña permite estudiar los distintos servicios proporcionados por la empresa.')
st.markdown('* El rango de fecha afectara en este caso a todas las graficas.')
st.markdown('* El primer grafico es una vista general de las ventas de los servicios.')
st.markdown('* El segundo grafico es un scatterplot donnde se relacionnan el numero de Ventas con el Importe total de estas. El tamaño de cada punto también se relaciona con el importe total')
st.markdown('* El ultimo grafico es una linea temporl de los servicios. La misma peataña multiselect permite elegir los servicios que se desean visualizar.')
st.markdown('')